### ISSUE TITLE
执行webpack报错了，打开页面没有任何显示

### ISSUE THREAD

**Issue by banzheshenghuo** [cwsjoker/webpack-vue-spa-demo#2]
使用webpack --display-error-details
`ERROR in Cannot find module 'node-sass'
 @ ./~/vue-style-loader!./~/css-loader!./~/vue-loader/lib/style-rewriter.js!./~/sass-loader!./~/vue-loader/lib/selector.js?type=style&index=0!./src/vue/home.vue 4:14-241
Child extract-text-webpack-plugin:
        + 2 hidden modules
`
请问要怎么处理

**Comment by cwsjoker** [comment]
依赖node-sass，请重载一遍依赖

**Comment by imbamboo** [comment]
npm install 完成
npm start 一切顺利，显示 webpack compiled successfully, 打开 localhost:8080，一片空白 。

**Comment by cwsjoker** [comment]
@imbamboo webpack.config的publicPath : __dirname + '/build/'中的__dirname去掉
