### ISSUE TITLE
为什么在npm install的时候还要求要安装python？

### ISSUE THREAD

**Issue by Somefuture** [cwsjoker/webpack-vue-spa-demo#3]
gyp verb `which` failed  python2 { Error: not found: python2

**Comment by cwsjoker** [comment]
没有啊，package.json里并没有python的任何相关

**Comment by Somefuture** [comment]
我也是打包成功了，然后从index.html进去什么都没QAQ

**Comment by cwsjoker** [comment]
报python2是因为node-sass的解析需要，所以还是装一下吧，如果电脑没装的话

**Comment by Somefuture** [comment]
node-sass我已经解决了，然后我打包成功，浏览器打开index.html的时候报   GET file:///C:/build/1.build.js?fc474f053b665cfaddf5 net::ERR_FILE_NOT_FOUND   请问是为什么呀？

**Comment by cwsjoker** [comment]
webpack.config.js
webpack打包
publicPath : __dirname + '/build/';
npm run start热载
publicPath :  '/build/';

**Comment by Somefuture** [comment]
谢谢博主~~~~
